name = "Sew Craft"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b428ec5b3be1542439c001fd537bc6c845ee7ea3fe12b593f854817e976fef7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.193"
