name = "Sew Craft"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ada92d994371519aab8fcf2005af55d492b8236d1fceaef88fd160e4b817e0e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.193"
