name = "Sew Craft"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5893e7136ca0294c69a3097d350bfb0f52f5f6ec881f0b65c1127bc4c2044175"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.193"
