name = "Sew Craft"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ae86dec553c7abc593f0b944f3e9acda1ebb9d7faef2ad02a1b9f54878b56e6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.193"
