name = "Sew Craft"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fae699264413dac08963f24e1021f230e8404a8f84b7a147ce3a7c59994ebd58"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.193"
