name = "Sew Craft"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df172fabf18a8966efe1c33b9d625c17480cd37d23207455b9e749a6fb48aed0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.193"
