name = "Sew Craft"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ffdb55b163547032e481fc4eba7ea1d9ff54ab9ac30fc211b4c148308f30cb3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.193"
